[project]
name = 'Time-Capsule-and-Future-Message-Delivery-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.inheritance]
path = 'contracts/inheritance.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage-token]
path = 'contracts/storage-token.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
